[book]
authors = ["ครอบครัวบุญเจริญสวัสดิ์"]
language = "th"
multilingual = false
src = "src"
title = "งานณาปณกิจศพ นายสมบูรณ์ บุญเจริญสวัสดิ์"
description = "รายละเอียดนายสมบูรณ์ บุญเจริญสวัสดิ์ (พ.ศ. 2567)"

[output.html]
default-theme = "navy"
site-url = "/somboon-buncharoensawat/"
no-section-label = true

[output.html.print]
enable = true
page-break = true

[output.html.fold]
enable = true
level = 0

[preprocessor.katex]
after = ["links"]

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]

[output.html.search]
enable = true
use-boolean-and = true
boost-title = 2
boost-hierarchy = 1
boost-paragraph = 1
expand = true
heading-split-level = 3
copy-js = true
